### PR TITLE
Add rust compiled protos

### PR DESCRIPTION
**Pull request by praveenperera**
@simplesagar @TristanSpeakEasy The plan is publish this to crates.io and in the rust-sdk use it as a package from crates.io

The files are generates from the `.proto` files

### CODE REVIEW

**Comment by TristanSpeakEasy** [comment]
@praveenperera Looks Good, can you add the generate command to https://github.com/speakeasy-api/speakeasy-schemas/blob/main/scripts/generate-protos.sh as then we can generate the files for this along with the other languages whenever changes are made to the protos

**Comment by TristanSpeakEasy** [comment]
> @praveenperera Looks Good, can you add the generate command to https://github.com/speakeasy-api/speakeasy-schemas/blob/main/scripts/generate-protos.sh as then we can generate the files for this along with the other languages whenever changes are made to the protos

You can see how we call the java generation here https://github.com/speakeasy-api/speakeasy-schemas/blob/main/scripts/generate-protos.sh#L34

**Comment by praveenperera** [comment]
@TristanSpeakEasy I can do that, but now if someone wants to generate bindings they will be need

- go
- gradle
- cargo

Would it make sense to split them up?

**Comment by praveenperera** [comment]
@TristanSpeakEasy I am getting this error when I try to generate `protoc-gen-go: program not found or is not executable`

I'm not super familiar with Go. I tried `go install github.com/golang/protobuf/protoc-gen-go`

**Comment by TristanSpeakEasy** [comment]
> @TristanSpeakEasy I am getting this error when I try to generate `protoc-gen-go: program not found or is not executable`
> 
> I'm not super familiar with Go. I tried `go install github.com/golang/protobuf/protoc-gen-go`

Does the local setup steps in the readme not get you to a working solution? if not we may need to look into what is missing for the onboarding steps and update the readme.

Also add the steps for rust if you can.

At the moment the idea with this repo is that it will eventually have CI/CD that will generate the compiles clients for each of the languages instead of having to do it manually but for now, until we have that CI/CD people who are modifying the protos (or adding new languages) will just have to look at running the entire generation pipeline locally

**Pull request merged**
